# Generated by Django 4.2.5 on 2023-09-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
