# Generated by Django 4.2.5 on 2023-09-26 03:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('emailModel', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expiration', models.DateTimeField(default=datetime.datetime(2023, 9, 26, 20, 12, 4, 970857))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emailModel.user')),
            ],
        ),
    ]
