# Generated by Django 4.2.5 on 2023-09-28 04:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailModel', '0003_user_is_active_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 21, 5, 50, 646365)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
