# Generated by Django 4.2.5 on 2023-09-28 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailModel', '0004_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationtoken',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 21, 21, 6, 630916)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
